### ISSUE TITLE
About Consistency Constraint

### ISSUE THREAD

**Issue by Joannes-Li** [WeeeicheN/MInD#2]
请问您使用barlow twins loss作为Consistency Constraint时，也是像barlow twins原论文一样将embedding升到很高维度再计算损失的吗？

**Comment by WeeeicheN** [comment]
> 请问您使用barlow twins loss作为Consistency Constraint时，也是像barlow twins原论文一样将embedding升到很高维度再计算损失的吗？

你好，感谢关注！不是的，根据“A note on connecting barlow twins with negative-sample-free contrastive learning”，我们尝试了“不升到很高维度”的方式
